version: "3.3"

services:
  twitchdata:
    build:
      context: .
    environment:
      - "CASSANDRA_HOSTS=cassandra-seed,cassandra1"
    links:
      - cassandra-seed
      - cassandra1
    networks:
      - twitchdata-network
    depends_on:
      - cassandra-seed
      - cassandra1
    restart: on-failure

  cassandra-seed:
    image: cassandra:latest
    volumes:
      - "cassandra_data_seed:/var/lib/cassandra"
      - "./cassandra-init.sh:/cassandra-init.sh"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      #      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      - twitchdata-network
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
  #    restart: always

  cassandra1:
    image: cassandra:latest
    volumes:
      - "cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      #      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      - twitchdata-network
    depends_on:
      - cassandra-seed
  #    restart: always

#  cassandra2:
#    image: cassandra:latest
#    volumes:
#      - "cassandra_data_2:/var/lib/cassandra"
#    environment:
#      - "CASSANDRA_SEEDS=cassandra-seed"
#      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      #      needed for setting up custom cluster name
#      - "CASSANDRA_DC=se1"
#      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
#    depends_on:
#      - cassandra-seed
#    restart: always

networks:
  twitchdata-network:

volumes:
  cassandra_data_seed:
  cassandra_data_1:
#  cassandra_data_2: